language: node_js
node_js:
  - '0.10'
branches:
  only:
    - master
before_install:
  - npm install bower -g
  - npm install karma-cli -g
  - npm install gulp -g
install:
  - bower install
  - npm install
  - gulp dist
before_script: npm start
script: karma start
cache:
  directories:
  - bower_components
  - node_modules
